### ISSUE TITLE
List concatenation

### ISSUE THREAD

**Issue by dustinblack** [arcalot/arcaflow-expressions#39]
## Please describe what you would like to see in this project

Two foreach sub-workflows produce list outputs:
```yaml
$.steps.sub1.outputs.success.data
$.steps.sub2.outputs.success.data
```
I would like the ability to concatenate these lists into one when passing the data to a step or output, hopefully with something very simple liike:
```yaml
my_step:
    plugin:
      deployment_type: image
      src: my_plugin_path
    input:
      my_list: !expr $.steps.sub1.outputs.success.data + $.steps.sub2.outputs.success.data
```
Where the `my_list` input to the step is a single list object consisting of all of the list items from the outputs of both sub-workflows.
